version: '3'
services:
  frontend:
    image: sithukyaw1992/beautyduty-frontend:0.0.1 # Replace with your Node.js frontend image details from Docker Hub
    container_name: frontend-container
    build:
      context: .
      dockerfile: Dockerfile # Use the name of your Dockerfile if it's not named "Dockerfile"
    ports:
      - "4200:4200" # Map port 4200 on the host to NGINX's port 80 in the container

# If you want to run NGINX separately, comment out or remove the following "nginx" section.
# nginx:
#   image: nginx:latest
#   container_name: nginx-container
#   volumes:
#     - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf # Optional: Mount custom NGINX configuration
#   ports:
#     - "80:80" # Map port 80 on the host to NGINX's port 80 in the container
#   depends_on:
#     - frontend

